// eslint-disable-next-line no-unused-vars
const portalsInfo = [
  {
    name: 'INSB',
    color: '#9c126d',
    logo: '/themes/cnrs/images/bibcnrs-logo-biologie.png',
    link: 'https://bib.cnrs.fr/category/biologie/',
    desc: 'Biologie',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INC',
    color: '#007e94',
    logo: '/themes/cnrs/images/bibcnrs-logo-chimie.png',
    link: 'https://bib.cnrs.fr/category/chimie/',
    desc: 'Chimie',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INEE',
    color: '#62ae25',
    logo: '/themes/cnrs/images/bibcnrs-logo-ecologie.png',
    link: 'https://bib.cnrs.fr/category/ecologie/',
    desc: 'Ecologie & Environnement',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INSHS',
    color: '#820e12',
    logo: '/themes/cnrs/images/bibcnrs-logo-homme.png',
    link: 'https://bib.cnrs.fr/category/homme/',
    desc: 'Homme & Société',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INSIS',
    color: '#d4002d',
    logo: '/themes/cnrs/images/bibcnrs-logo-ingenierie.png',
    link: 'https://bib.cnrs.fr/category/ingenierie/',
    desc: 'Ingénierie & Systèmes',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INSMI',
    color: '#547d3d',
    logo: '/themes/cnrs/images/bibcnrs-logo-mathematiques.png',
    link: 'https://bib.cnrs.fr/category/mathematiques/',
    desc: 'Mathématiques',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'IN2P3',
    color: '#e75113',
    logo: '/themes/cnrs/images/bibcnrs-logo-nucleaire.png',
    link: 'https://bib.cnrs.fr/category/nucleaire/',
    desc: 'Nucléaire & Particules',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INP',
    color: '#004494',
    logo: '/themes/cnrs/images/bibcnrs-logo-physique.png',
    link: 'https://bib.cnrs.fr/category/physique/',
    desc: 'Physique',
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INS2I',
    color: '#562a84',
    logo: '/themes/cnrs/images/bibcnrs-logo-information.png',
    link: 'https://bib.cnrs.fr/category/information/',
    desc: "Sciences de l'information",
    count: 0,
    html: 0,
    pdf: 0,
  },
  {
    name: 'INSU',
    color: '#cc2381',
    logo: '/themes/cnrs/images/bibcnrs-logo-terre.png',
    link: 'https://bib.cnrs.fr/category/terre/',
    desc: 'Terre & Univers',
    count: 0,
    html: 0,
    pdf: 0,
  },
];
